In [919]:
import pandas as pd
import numpy as np

In [920]:
df = pd.read_excel("Internal audit dataset.xlsx")

In [921]:
df.head()

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
0,BR001,Hyderabad - Forex/Treasury,Hyderabad,Forex/Treasury,424,0,96.39,High,31,23.5,0,185,90
1,BR002,Pune - HR & Admin,Pune,HR & Admin,204,0,15.40,Low,56,19.3,0,22,36
2,BR003,Bangalore - Retail Branch,Bangalore,Retail Branch,785,0,19.57,Low,71,17.4,1,34,42
3,BR004,Coimbatore - Loans & Credit,Coimbatore,Loans & Credit,180,1,18.33,Medium,15,3.1,1,48,48
4,BR005,Coimbatore - Digital Banking,Coimbatore,Digital Banking,381,2,6.09,Medium,21,26.0,0,26,44

In [922]:
df.shape

(50, 13)

In [923]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   BranchID                 50 non-null     str
 1   BranchName               50 non-null     str
 2   City                     50 non-null     str
 3   BranchType               50 non-null     str
 4   DaysSinceLastAudit       50 non-null     int64
 5   PastFindingsCount        50 non-null     int64
 6   TransactionVolumeCr      50 non-null     float64
 7   RegulatorySensitivity    50 non-null     str
 8   StaffCount               50 non-null     int64
 9   StaffTurnoverRate        50 non-null     float64
 10  ComplaintsLastYear       50 non-null     int64
 11  EstimatedRiskExposureCr  50 non-null     int64
 12  EstimatedAuditHours      50 non-null     int64
dtypes: float64(2), int64(6), str(5)
memory usage: 5.2 KB

In [924]:
# =====================================
# Step 6: Check Missing Values
# =====================================

df.isnull().sum()

BranchID                   0
BranchName                 0
City                       0
BranchType                 0
DaysSinceLastAudit         0
PastFindingsCount          0
TransactionVolumeCr        0
RegulatorySensitivity      0
StaffCount                 0
StaffTurnoverRate          0
ComplaintsLastYear         0
EstimatedRiskExposureCr    0
EstimatedAuditHours        0
dtype: int64

In [925]:
# =====================================
# Step 7: Check Duplicate Rows
# =====================================

df.duplicated().sum()

np.int64(0)

In [926]:
# =====================================
# Step 8: Statistical Summary
# =====================================

df.describe()

,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,391.700000,1.440000,39.292600,45.280000,19.164000,0.560000,86.560000,55.900000
std,242.971927,1.630826,34.610514,20.912881,9.856724,0.674915,58.429501,19.306602
min,65.000000,0.000000,5.040000,8.000000,2.400000,0.000000,18.000000,30.000000
25%,204.000000,0.000000,14.915000,30.250000,10.075000,0.000000,43.000000,40.000000
50%,368.000000,1.000000,29.445000,47.500000,20.450000,0.000000,74.500000,50.000000
75%,486.750000,2.000000,52.962500,63.250000,25.875000,1.000000,107.750000,73.500000
max,1112.000000,5.000000,159.490000,79.000000,34.500000,3.000000,265.000000,94.000000

In [927]:
# =====================================
# Step 9: Unique Branch Types
# =====================================

df["BranchType"].unique()

<StringArray>
[   'Forex/Treasury',        'HR & Admin',     'Retail Branch',
    'Loans & Credit',   'Digital Banking', 'Corporate Banking',
 'Wealth Management',        'Compliance',     'IT Operations']
Length: 9, dtype: str

In [928]:
# =====================================
# Step 10: Unique Regulatory Sensitivity
# =====================================

df["RegulatorySensitivity"].unique()

<StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str

In [929]:
# =====================================
# Step 11: Branch Type Count
# =====================================

df["BranchType"].value_counts()

BranchType
Retail Branch        17
Loans & Credit        8
Corporate Banking     6
Digital Banking       5
Wealth Management     5
Forex/Treasury        3
HR & Admin            3
IT Operations         2
Compliance            1
Name: count, dtype: int64

In [930]:
# =====================================
# Step 12: Regulatory Sensitivity Count
# =====================================

df["RegulatorySensitivity"].value_counts()

RegulatorySensitivity
Medium    18
Low       17
High      15
Name: count, dtype: int64

In [931]:
# =====================================
# Step 13: Number of Branches by City
# =====================================

df["City"].value_counts()

City
Coimbatore     7
Chennai        7
Tirunelveli    5
Hyderabad      4
Pune           4
Bangalore      4
Madurai        4
Thanjavur      3
Erode          2
Mumbai         2
Trichy         2
Vellore        2
Salem          2
Delhi          1
Nagercoil      1
Name: count, dtype: int64

In [932]:
# =====================================
# Step 14: Average Transaction Volume by Branch Type
# =====================================

df.groupby("BranchType")["TransactionVolumeCr"].mean()

BranchType
Compliance           26.910000
Corporate Banking    50.385000
Digital Banking      21.334000
Forex/Treasury       56.603333
HR & Admin           19.226667
IT Operations        41.380000
Loans & Credit       28.705000
Retail Branch        43.649412
Wealth Management    49.362000
Name: TransactionVolumeCr, dtype: float64

In [933]:
# =====================================
# Step 15: Average Days Since Last Audit
# =====================================

df.groupby("BranchType")["DaysSinceLastAudit"].mean()

BranchType
Compliance           497.000000
Corporate Banking    300.666667
Digital Banking      339.600000
Forex/Treasury       403.333333
HR & Admin           195.333333
IT Operations        597.000000
Loans & Credit       292.250000
Retail Branch        537.294118
Wealth Management    224.800000
Name: DaysSinceLastAudit, dtype: float64

In [934]:
# =====================================
# Step 15: Average Days Since Last Audit
# =====================================

df.groupby("BranchType")["DaysSinceLastAudit"].mean()

BranchType
Compliance           497.000000
Corporate Banking    300.666667
Digital Banking      339.600000
Forex/Treasury       403.333333
HR & Admin           195.333333
IT Operations        597.000000
Loans & Credit       292.250000
Retail Branch        537.294118
Wealth Management    224.800000
Name: DaysSinceLastAudit, dtype: float64

In [935]:
# =====================================
# Step 17: Total Complaints
# =====================================

df.groupby("BranchType")["ComplaintsLastYear"].sum()

BranchType
Compliance           1
Corporate Banking    5
Digital Banking      1
Forex/Treasury       1
HR & Admin           1
IT Operations        1
Loans & Credit       8
Retail Branch        9
Wealth Management    1
Name: ComplaintsLastYear, dtype: int64

In [936]:
# =====================================
# Step 18: Top 10 Branches by Transaction Volume
# =====================================

df.nlargest(10, "TransactionVolumeCr")

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
28,BR029,Bangalore - Corporate Banking,Bangalore,Corporate Banking,248,2,159.49,High,30,3.6,2,265,94
17,BR018,Vellore - Retail Branch,Vellore,Retail Branch,545,2,146.73,Medium,73,24.8,1,210,78
35,BR036,Erode - Wealth Management,Erode,Wealth Management,381,5,131.01,Medium,47,4.4,1,205,86
0,BR001,Hyderabad - Forex/Treasury,Hyderabad,Forex/Treasury,424,0,96.39,High,31,23.5,0,185,90
31,BR032,Coimbatore - Retail Branch,Coimbatore,Retail Branch,65,0,74.96,Low,41,10.6,0,71,34
22,BR023,Thanjavur - Corporate Banking,Thanjavur,Corporate Banking,628,5,70.37,High,64,22.7,0,225,92
27,BR028,Hyderabad - Retail Branch,Hyderabad,Retail Branch,1112,0,68.89,Low,23,7.2,0,98,44
29,BR030,Madurai - Retail Branch,Madurai,Retail Branch,404,0,60.93,Low,9,2.9,0,65,36
6,BR007,Erode - Retail Branch,Erode,Retail Branch,456,1,59.61,Medium,48,32.2,1,92,58
46,BR047,Chennai - IT Operations,Chennai,IT Operations,796,0,59.02,Low,45,22.1,1,88,50

In [937]:
df.sort_values(by="TransactionVolumeCr", ascending=False).head(10)

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
28,BR029,Bangalore - Corporate Banking,Bangalore,Corporate Banking,248,2,159.49,High,30,3.6,2,265,94
17,BR018,Vellore - Retail Branch,Vellore,Retail Branch,545,2,146.73,Medium,73,24.8,1,210,78
35,BR036,Erode - Wealth Management,Erode,Wealth Management,381,5,131.01,Medium,47,4.4,1,205,86
0,BR001,Hyderabad - Forex/Treasury,Hyderabad,Forex/Treasury,424,0,96.39,High,31,23.5,0,185,90
31,BR032,Coimbatore - Retail Branch,Coimbatore,Retail Branch,65,0,74.96,Low,41,10.6,0,71,34
22,BR023,Thanjavur - Corporate Banking,Thanjavur,Corporate Banking,628,5,70.37,High,64,22.7,0,225,92
27,BR028,Hyderabad - Retail Branch,Hyderabad,Retail Branch,1112,0,68.89,Low,23,7.2,0,98,44
29,BR030,Madurai - Retail Branch,Madurai,Retail Branch,404,0,60.93,Low,9,2.9,0,65,36
6,BR007,Erode - Retail Branch,Erode,Retail Branch,456,1,59.61,Medium,48,32.2,1,92,58
46,BR047,Chennai - IT Operations,Chennai,IT Operations,796,0,59.02,Low,45,22.1,1,88,50

In [938]:
# =====================================
# Step 19: Longest Time Since Last Audit
# =====================================

df.nlargest(10, "DaysSinceLastAudit")

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
27,BR028,Hyderabad - Retail Branch,Hyderabad,Retail Branch,1112,0,68.89,Low,23,7.2,0,98,44
11,BR012,Mumbai - Retail Branch,Mumbai,Retail Branch,986,2,29.21,Low,9,25.5,0,41,38
49,BR050,Tirunelveli - Retail Branch,Tirunelveli,Retail Branch,852,1,10.88,Low,74,19.0,1,31,40
47,BR048,Coimbatore - Retail Branch,Coimbatore,Retail Branch,802,0,26.42,Low,58,25.0,1,38,38
46,BR047,Chennai - IT Operations,Chennai,IT Operations,796,0,59.02,Low,45,22.1,1,88,50
2,BR003,Bangalore - Retail Branch,Bangalore,Retail Branch,785,0,19.57,Low,71,17.4,1,34,42
33,BR034,Madurai - Loans & Credit,Madurai,Loans & Credit,705,5,13.58,High,24,19.6,1,133,88
7,BR008,Tirunelveli - Retail Branch,Tirunelveli,Retail Branch,666,1,9.99,Low,54,25.5,1,27,40
22,BR023,Thanjavur - Corporate Banking,Thanjavur,Corporate Banking,628,5,70.37,High,64,22.7,0,225,92
36,BR037,Salem - Retail Branch,Salem,Retail Branch,620,0,31.11,Low,78,34.5,1,46,40

In [939]:
# =====================================
# Step 20: Highest Past Audit Findings
# =====================================

df.nlargest(10, "PastFindingsCount")

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
22,BR023,Thanjavur - Corporate Banking,Thanjavur,Corporate Banking,628,5,70.37,High,64,22.7,0,225,92
33,BR034,Madurai - Loans & Credit,Madurai,Loans & Credit,705,5,13.58,High,24,19.6,1,133,88
35,BR036,Erode - Wealth Management,Erode,Wealth Management,381,5,131.01,Medium,47,4.4,1,205,86
44,BR045,Chennai - Forex/Treasury,Chennai,Forex/Treasury,353,5,15.11,High,8,33.5,1,156,90
9,BR010,Delhi - Digital Banking,Delhi,Digital Banking,148,4,14.85,High,37,31.1,1,82,70
20,BR021,Chennai - Loans & Credit,Chennai,Loans & Credit,297,4,29.68,High,67,30.1,1,142,80
34,BR035,Madurai - Corporate Banking,Madurai,Corporate Banking,241,4,13.29,High,32,20.3,0,118,76
42,BR043,Trichy - Corporate Banking,Trichy,Corporate Banking,173,4,16.39,High,37,30.6,0,109,74
13,BR014,Tirunelveli - Loans & Credit,Tirunelveli,Loans & Credit,153,3,53.15,High,23,29.6,1,138,82
25,BR026,Tirunelveli - Wealth Management,Tirunelveli,Wealth Management,310,3,12.79,Medium,37,3.4,0,47,46

In [940]:
# =====================================
# Step 21: Highest Customer Complaints
# =====================================

df.nlargest(10, "ComplaintsLastYear")

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours
16,BR017,Coimbatore - Loans & Credit,Coimbatore,Loans & Credit,314,0,40.51,Medium,26,26.0,3,96,60
10,BR011,Pune - Corporate Banking,Pune,Corporate Banking,217,1,5.68,High,79,19.6,2,76,72
28,BR029,Bangalore - Corporate Banking,Bangalore,Corporate Banking,248,2,159.49,High,30,3.6,2,265,94
2,BR003,Bangalore - Retail Branch,Bangalore,Retail Branch,785,0,19.57,Low,71,17.4,1,34,42
3,BR004,Coimbatore - Loans & Credit,Coimbatore,Loans & Credit,180,1,18.33,Medium,15,3.1,1,48,48
6,BR007,Erode - Retail Branch,Erode,Retail Branch,456,1,59.61,Medium,48,32.2,1,92,58
7,BR008,Tirunelveli - Retail Branch,Tirunelveli,Retail Branch,666,1,9.99,Low,54,25.5,1,27,40
8,BR009,Tirunelveli - HR & Admin,Tirunelveli,HR & Admin,178,0,34.22,Low,59,20.6,1,29,35
9,BR010,Delhi - Digital Banking,Delhi,Digital Banking,148,4,14.85,High,37,31.1,1,82,70
13,BR014,Tirunelveli - Loans & Credit,Tirunelveli,Loans & Credit,153,3,53.15,High,23,29.6,1,138,82

In [941]:
# =====================================
# Step 22: Convert Regulatory Sensitivity to Numeric
# =====================================

regulatory_map = {
    "Low": 1,
    "Medium": 2,
    "High": 3
}

df["RegulatoryScore"] = df["RegulatorySensitivity"].map(regulatory_map)

In [942]:
df.head()

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours,RegulatoryScore
0,BR001,Hyderabad - Forex/Treasury,Hyderabad,Forex/Treasury,424,0,96.39,High,31,23.5,0,185,90,3
1,BR002,Pune - HR & Admin,Pune,HR & Admin,204,0,15.40,Low,56,19.3,0,22,36,1
2,BR003,Bangalore - Retail Branch,Bangalore,Retail Branch,785,0,19.57,Low,71,17.4,1,34,42,1
3,BR004,Coimbatore - Loans & Credit,Coimbatore,Loans & Credit,180,1,18.33,Medium,15,3.1,1,48,48,2
4,BR005,Coimbatore - Digital Banking,Coimbatore,Digital Banking,381,2,6.09,Medium,21,26.0,0,26,44,2

In [943]:
# =====================================
# Step 24: Normalize Risk Factors
# =====================================

columns_to_scale = [
    "DaysSinceLastAudit",
    "PastFindingsCount",
    "TransactionVolumeCr",
    "StaffTurnoverRate",
    "ComplaintsLastYear"
]

for col in columns_to_scale:
    df[col + "_Scaled"] = (
        (df[col] - df[col].min()) /
        (df[col].max() - df[col].min())
    )

In [944]:
# Normalize Regulatory Score

df["RegulatoryScore_Scaled"] = (
    (df["RegulatoryScore"] - df["RegulatoryScore"].min()) /
    (df["RegulatoryScore"].max() - df["RegulatoryScore"].min())
)

In [945]:
df.head()

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,ComplaintsLastYear,EstimatedRiskExposureCr,EstimatedAuditHours,RegulatoryScore,DaysSinceLastAudit_Scaled,PastFindingsCount_Scaled,TransactionVolumeCr_Scaled,StaffTurnoverRate_Scaled,ComplaintsLastYear_Scaled,RegulatoryScore_Scaled
0,BR001,Hyderabad - Forex/Treasury,Hyderabad,Forex/Treasury,424,0,96.39,High,31,23.5,0,185,90,3,0.342884,0.0,0.591454,0.657321,0.000000,1.0
1,BR002,Pune - HR & Admin,Pune,HR & Admin,204,0,15.40,Low,56,19.3,0,22,36,1,0.132760,0.0,0.067077,0.526480,0.000000,0.0
2,BR003,Bangalore - Retail Branch,Bangalore,Retail Branch,785,0,19.57,Low,71,17.4,1,34,42,1,0.687679,0.0,0.094076,0.467290,0.333333,0.0
3,BR004,Coimbatore - Loans & Credit,Coimbatore,Loans & Credit,180,1,18.33,Medium,15,3.1,1,48,48,2,0.109838,0.2,0.086047,0.021807,0.333333,0.5
4,BR005,Coimbatore - Digital Banking,Coimbatore,Digital Banking,381,2,6.09,Medium,21,26.0,0,26,44,2,0.301815,0.4,0.006798,0.735202,0.000000,0.5

In [946]:
df["RiskScore"] = (
    df["DaysSinceLastAudit_Scaled"] * 0.30 +
    df["PastFindingsCount_Scaled"] * 0.25 +
    df["TransactionVolumeCr_Scaled"] * 0.20 +
    df["RegulatoryScore_Scaled"] * 0.15 +
    df["StaffTurnoverRate_Scaled"] * 0.05 +
    df["ComplaintsLastYear_Scaled"] * 0.05
)

In [947]:
df[["BranchID","BranchName","RiskScore"]].head()

  BranchID                    BranchName  RiskScore
0    BR001    Hyderabad - Forex/Treasury   0.404022
1    BR002             Pune - HR & Admin   0.079567
2    BR003     Bangalore - Retail Branch   0.265150
3    BR004   Coimbatore - Loans & Credit   0.192918
4    BR005  Coimbatore - Digital Banking   0.303664

In [948]:
# =====================================
# Step 28: Rank Branches by Risk Score
# =====================================

df["RiskRank"] = df["RiskScore"].rank(method="dense", ascending=False)

In [949]:
# =====================================
# Step 29: Audit Selection
# =====================================

df["AuditDecision"] = np.where(
    df["RiskRank"] <= 20,
    "Selected for Audit",
    "Deferred"
)

In [950]:
# =====================================
# Step 30: Risk Tier
# =====================================

def risk_tier(score):
    if score >= 0.50:
        return "High"
    elif score >= 0.40:
        return "Medium"
    else:
        return "Low"

df["RiskTier"] = df["RiskScore"].apply(risk_tier)

In [951]:
# =====================================
# Step 31: Risk Tier Distribution
# =====================================

df["RiskTier"].value_counts()

RiskTier
Low       35
Medium     8
High       7
Name: count, dtype: int64

In [952]:
# =====================================
# Step 32: Audit Decision Count
# =====================================

df["AuditDecision"].value_counts()

AuditDecision
Deferred              30
Selected for Audit    20
Name: count, dtype: int64

In [953]:
# =====================================
# Step 33: Top 20 Branches
# =====================================

df.sort_values("RiskRank").head(20)

,BranchID,BranchName,City,BranchType,DaysSinceLastAudit,PastFindingsCount,TransactionVolumeCr,RegulatorySensitivity,StaffCount,StaffTurnoverRate,...,DaysSinceLastAudit_Scaled,PastFindingsCount_Scaled,TransactionVolumeCr_Scaled,StaffTurnoverRate_Scaled,ComplaintsLastYear_Scaled,RegulatoryScore_Scaled,RiskScore,RiskRank,AuditDecision,RiskTier
22,BR023,Thanjavur - Corporate Banking,Thanjavur,Corporate Banking,628,5,70.37,High,64,22.7,...,0.537727,1.0,0.422985,0.632399,0.000000,1.0,0.677535,1.0,Selected for Audit,High
33,BR034,Madurai - Loans & Credit,Madurai,Loans & Credit,705,5,13.58,High,24,19.6,...,0.611270,1.0,0.055293,0.535826,0.333333,1.0,0.637898,2.0,Selected for Audit,High
35,BR036,Erode - Wealth Management,Erode,Wealth Management,381,5,131.01,Medium,47,4.4,...,0.301815,1.0,0.815604,0.062305,0.333333,0.5,0.598447,3.0,Selected for Audit,High
44,BR045,Chennai - Forex/Treasury,Chennai,Forex/Treasury,353,5,15.11,High,8,33.5,...,0.275072,1.0,0.065199,0.968847,0.333333,1.0,0.560670,4.0,Selected for Audit,High
17,BR018,Vellore - Retail Branch,Vellore,Retail Branch,545,2,146.73,Medium,73,24.8,...,0.458453,0.4,0.917384,0.697819,0.333333,0.5,0.547570,5.0,Selected for Audit,High
28,BR029,Bangalore - Corporate Banking,Bangalore,Corporate Banking,248,2,159.49,High,30,3.6,...,0.174785,0.4,1.000000,0.037383,0.666667,1.0,0.537638,6.0,Selected for Audit,High
20,BR021,Chennai - Loans & Credit,Chennai,Loans & Credit,297,4,29.68,High,67,30.1,...,0.221585,0.8,0.159534,0.862928,0.333333,1.0,0.508195,7.0,Selected for Audit,High
9,BR010,Delhi - Digital Banking,Delhi,Digital Banking,148,4,14.85,High,37,31.1,...,0.079274,0.8,0.063516,0.894081,0.333333,1.0,0.447856,8.0,Selected for Audit,Medium
13,BR014,Tirunelveli - Loans & Credit,Tirunelveli,Loans & Credit,153,3,53.15,High,23,29.6,...,0.084050,0.6,0.311492,0.847352,0.333333,1.0,0.446548,9.0,Selected for Audit,Medium
42,BR043,Trichy - Corporate Banking,Trichy,Corporate Banking,173,4,16.39,High,37,30.6,...,0.103152,0.8,0.073487,0.878505,0.000000,1.0,0.439568,10.0,Selected for Audit,Medium
34,BR035,Madurai - Corporate Banking,Madurai,Corporate Banking,241,4,13.29,High,32,20.3,...,0.168099,0.8,0.053415,0.557632,0.000000,1.0,0.438994,11.0,Selected for Audit,Medium
11,BR012,Mumbai - Retail Branch,Mumbai,Retail Branch,986,2,29.21,Low,9,25.5,...,0.879656,0.4,0.156491,0.719626,0.000000,0.0,0.431176,12.0,Selected for Audit,Medium
19,BR020,Pune - Corporate Banking,Pune,Corporate Banking,297,2,37.09,High,71,30.5,...,0.221585,0.4,0.207511,0.875389,0.333333,1.0,0.418414,13.0,Selected for Audit,Medium
0,BR001,Hyderabad - Forex/Treasury,Hyderabad,Forex/Treasury,424,0,96.39,High,31,23.5,...,0.342884,0.0,0.591454,0.657321,0.000000,1.0,0.404022,14.0,Selected for Audit,Medium
21,BR022,Madurai - Compliance,Madurai,Compliance,497,1,26.91,High,39,24.1,...,0.412607,0.2,0.141599,0.676012,0.333333,1.0,0.402569,15.0,Selected for Audit,Medium
27,BR028,Hyderabad - Retail Branch,Hyderabad,Retail Branch,1112,0,68.89,Low,23,7.2,...,1.000000,0.0,0.413402,0.149533,0.000000,0.0,0.390157,16.0,Selected for Audit,Low
26,BR027,Thanjavur - Forex/Treasury,Thanjavur,Forex/Treasury,433,1,58.31,High,41,9.9,...,0.351480,0.2,0.344901,0.233645,0.000000,1.0,0.386107,17.0,Selected for Audit,Low
6,BR007,Erode - Retail Branch,Erode,Retail Branch,456,1,59.61,Medium,48,32.2,...,0.373448,0.2,0.353318,0.928349,0.333333,0.5,0.370782,18.0,Selected for Audit,Low
46,BR047,Chennai - IT Operations,Chennai,IT Operations,796,0,59.02,Low,45,22.1,...,0.698185,0.0,0.349498,0.613707,0.333333,0.0,0.326707,19.0,Selected for Audit,Low
49,BR050,Tirunelveli - Retail Branch,Tirunelveli,Retail Branch,852,1,10.88,Low,74,19.0,...,0.751671,0.2,0.037812,0.517134,0.333333,0.0,0.325587,20.0,Selected for Audit,Low

In [954]:
# =====================================
# Step 34: Export Final Dataset
# =====================================

df.to_csv("Internal_Audit_Final.csv", index=False)

print("Final dataset exported successfully!")

Final dataset exported successfully!

In [955]:
# =====================================
# Step 31: Final Result
# =====================================

df[[
    "BranchID",
    "BranchName",
    "RiskScore",
    "RiskRank",
    "RiskTier",
    "AuditDecision"
]].sort_values(by="RiskRank").head(20)

,BranchID,BranchName,RiskScore,RiskRank,RiskTier,AuditDecision
22,BR023,Thanjavur - Corporate Banking,0.677535,1.0,High,Selected for Audit
33,BR034,Madurai - Loans & Credit,0.637898,2.0,High,Selected for Audit
35,BR036,Erode - Wealth Management,0.598447,3.0,High,Selected for Audit
44,BR045,Chennai - Forex/Treasury,0.560670,4.0,High,Selected for Audit
17,BR018,Vellore - Retail Branch,0.547570,5.0,High,Selected for Audit
28,BR029,Bangalore - Corporate Banking,0.537638,6.0,High,Selected for Audit
20,BR021,Chennai - Loans & Credit,0.508195,7.0,High,Selected for Audit
9,BR010,Delhi - Digital Banking,0.447856,8.0,Medium,Selected for Audit
13,BR014,Tirunelveli - Loans & Credit,0.446548,9.0,Medium,Selected for Audit
42,BR043,Trichy - Corporate Banking,0.439568,10.0,Medium,Selected for Audit
34,BR035,Madurai - Corporate Banking,0.438994,11.0,Medium,Selected for Audit
11,BR012,Mumbai - Retail Branch,0.431176,12.0,Medium,Selected for Audit
19,BR020,Pune - Corporate Banking,0.418414,13.0,Medium,Selected for Audit
0,BR001,Hyderabad - Forex/Treasury,0.404022,14.0,Medium,Selected for Audit
21,BR022,Madurai - Compliance,0.402569,15.0,Medium,Selected for Audit
27,BR028,Hyderabad - Retail Branch,0.390157,16.0,Low,Selected for Audit
26,BR027,Thanjavur - Forex/Treasury,0.386107,17.0,Low,Selected for Audit
6,BR007,Erode - Retail Branch,0.370782,18.0,Low,Selected for Audit
46,BR047,Chennai - IT Operations,0.326707,19.0,Low,Selected for Audit
49,BR050,Tirunelveli - Retail Branch,0.325587,20.0,Low,Selected for Audit